### ISSUE TITLE
Completion order on user defined classes is incorrect

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-services#106]
This ordering looks odd to me:

![screen shot 2015-03-30 at 12 00 18 pm](https://cloud.githubusercontent.com/assets/1269969/6904280/9a5b159a-d6d4-11e4-916d-15b0b3706b5b.png)

From this gist: dartpad.dartlang.org/7eb492810a52928c8e0e

I would expect lexical sorting - to help users find items - unless there were strong signals to move particular items higher in the list.

**Comment by lukechurch** [comment]
Yup, that's a bug.

**Comment by devoncarew** [comment]
It's in that linked gist.

**Comment by lukechurch** [comment]
Sorry, I didn't see it. thanks
