### ISSUE TITLE
Missing a starting * in the dartdoc

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-services#112]
![image](https://cloud.githubusercontent.com/assets/1035299/6983252/0250cbf0-da1c-11e4-9f3a-825eea204e0e.png)

Not sure if this is an issue from dart-services or the analyzer, but I'm getting this string:
`Deprecated*: override [attached] instead.`

But I should get a string that start with a star:
![image](https://cloud.githubusercontent.com/assets/1035299/6983288/7626c476-da1c-11e4-97c3-b2d5173e8d1f.png)

**Comment by devoncarew** [comment]
Fixed in #146
