### ISSUE TITLE
quick fixes don't suggest dart:html imports

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-services#116]
This seems to be really specific to the dart:html library, for example, if I would do write `Future a;` then the suggested fixes are:

```
{
 "fixes": [
  {
   "fixes": [
    {
     "message": "Import library 'dart:async'",
     "edits": [
      {
       "offset": 0,
       "length": 0,
       "replacement": "import 'dart:async';\n\n"
      }
     ]
    },
    {
     "message": "Create class 'Future'",
     "edits": [
      {
       "offset": 9,
       "length": 0,
       "replacement": "\n\nclass Future {\n}"
      }
     ]
    }
   ],
   "problemMessage": "Undefined class 'Future'",
   "offset": 0,
   "length": 6
  }
 ]
}
```

However, if I use the input `var a = querySelector("a");` then the fixes are:

```
{
 "fixes": [
  {
   "fixes": [
    {
     "message": "Create function 'querySelector'",
     "edits": [
      {
       "offset": 27,
       "length": 0,
       "replacement": "\n\nquerySelector(String s) {\n}"
      }
     ]
    }
   ],
   "problemMessage": "The function 'querySelector' is not defined",
   "offset": 8,
   "length": 13
  }
 ]
}
```

**Comment by devoncarew** [comment]
Adding @scheglov, who I think wrote the import quick-fixes.

**Comment by kasperpeulen** [comment]
@devoncarew The latest version that luke uploaded at
http://doc-test.dart-services.appspot.com/' did actually support dart:html
imports :) So I guess this is fixed.

2015-04-06 0:45 GMT+02:00 Devon Carew <notifications@github.com>:

> Adding @scheglov <https://github.com/scheglov>, who I think wrote the
> import quick-fixes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dart-services/issues/116#issuecomment-89867292>
> .
>



-- 
Kasper

**Comment by devoncarew** [comment]
Cool - closing this then.

**Comment by lukechurch** [comment]
This behaviour seems to have regressed with the latest sync to HEAD

**Comment by scheglov** [comment]
If an SDK library is not used in a context, then it is not analyzed.
So, quick fix processor does not know that there is a library with unresolved function.
Solution: analyze an artificial library that imports all the libraries you want to be import-quick-fixable.

**Comment by kasperpeulen** [comment]
@scheglov But why is then only the dart:html library not suggested for import ? Other libraries like async or math are suggested to be imported. For example, see:
http://dev.dart-pad.appspot.com/41ab9714492b633c01b0

**Comment by scheglov** [comment]
dart:math is imported by dart:core, which is implicitly imported by any Dart library.
dart:async is imported by dart:convert, which is imported by dart:core.

**Comment by kasperpeulen** [comment]
Okay, so it may be that it is not only dart:html specific ?
Or are all other dart sdk libraries implicitly imported by dart:core ?

2015-04-12 16:39 GMT+02:00 Konstantin Scheglov <notifications@github.com>:

> dart:math is imported by dart:core, which is implicitly imported by any
> Dart library.
> dart:async is imported by dart:convert, which is imported by dart:core.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dart-services/issues/116#issuecomment-92072466>
> .
>



-- 
Kasper

**Comment by scheglov** [comment]
Well, yes, I guess it is not only dart:html specific.
  While dart:core explicitly imports other libraries, I'm not sure that it
imports all the SDK libraries.

On Sun, Apr 12, 2015 at 7:46 AM, Kasper Peulen <notifications@github.com>
wrote:

> Okay, so it may be that it is not only dart:html specific ?
> Or are all other dart sdk libraries implicitly imported by dart:core ?
>
> 2015-04-12 16:39 GMT+02:00 Konstantin Scheglov <notifications@github.com>:
>
> > dart:math is imported by dart:core, which is implicitly imported by any
> > Dart library.
> > dart:async is imported by dart:convert, which is imported by dart:core.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/dart-lang/dart-services/issues/116#issuecomment-92072466
> >
> > .
> >
>
>
>
> --
> Kasper
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dart-services/issues/116#issuecomment-92075525>
> .
>



-- 
Konstantin Scheglov
Software Engineer
Google, Inc.
