### ISSUE TITLE
HEAD on Analysis Server is not completing 'pr' correctly

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-services#126]
There seems to be a serious regression with the HEAD sync of Analysis Server resulting in out-of-scope completions being suggested

**Comment by lukechurch** [comment]
https://code.google.com/p/dart/issues/detail?id=23131

**Comment by devoncarew** [comment]
fixed?

**Comment by lukechurch** [comment]
Getting there. It requires some changes to the way in which we drive Analysis Server. It'll be done by tomorrow.

**Comment by devoncarew** [comment]
Ah, kk, I thought it had already been fixed and this issue was just dangling.

**Comment by lukechurch** [comment]
Fixed in #132
