### ISSUE TITLE
return generated source maps

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-services#130]
When compiling, some clients may want the generated source maps. To reduce cost for clients tha don't want them, this should be an opt-in feature (optional param). We'd need to change the return type of the `compile` call to return both the compiled JS results and the generated sourcemap file, if any.

**Comment by lukechurch** [comment]
happy to do this - do you if we have any clients that could make use of it today, or is it more a 'for the future' you're thinking of?

**Comment by devoncarew** [comment]
For the future. So that a client could map from JS error locations to the dart source code.
