### ISSUE TITLE
Travis: both stable and dev

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dart-services#137]
Make sure we don't break anything in v-next

**Comment by lukechurch** [comment]
@kevmoo I don't understand this comment. Is there a pointer where I could read more?

**Comment by devoncarew** [comment]
He'd like this project to test on two bots, one on the stable sdk and one on the dev one. Dartdoc is doing it currently:

https://github.com/dart-lang/dartdoc/blob/master/.travis.yml
