### ISSUE TITLE
add an example of using the services API

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-services#154]
Probably in the readme. It'd be nice to have a simple POST example (perhaps linking to Kasper's pad showing the use of the API?), as well as an example of calling it from Dart code.

Related to #77.

**Comment by lukechurch** [comment]
I've added a simple POST pad to the home page, I took Kasper's pad and adjusted a little and backed by a gist I own so that we can adjust more easily.

I think we can look at adding a use of the API when package support lands?
