### ISSUE TITLE
quick fix suggested but none exists

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-services#163]
https://dartpad.dartlang.org/9579731bd040572a3d48

**Comment by lukechurch** [comment]
I think this is just talking to an old server version when I was rolling out the new code. Can you still repro? I can't any more

**Comment by lukechurch** [comment]
@devoncarew good catch.
Will resolve this evening. The server needs a redeploy, it's a very straight forwards fix from a git mistake.
Lets hold the UI push until this is landed and the services are warm. ETA 2330 GMT. 

I've added #164 for automating the use of git on the server as we do on the client to prevent a repeat.

**Comment by lukechurch** [comment]
deploying v191-f now with the fix

**Comment by lukechurch** [comment]
Fixed.
