### ISSUE TITLE
move the summarization code from dart-pad

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-services#226]
Move the summarization code from dart-pad to here; have a `summarization` field come back on every call to analyze.

**Comment by lukechurch** [comment]
I don't think we want to put that field on the response of every call to analyse. That call already does too much.

I'd rather we added a specific summarise end point.

**Comment by devoncarew** [comment]
Let's talk then. It's in the interest of optimization. Perhaps as a separate service call, and have an optional param on analyze to return the summary?

**Comment by lukechurch** [comment]
Sure - lets chat. We're only showing the summary on share right? Or are we planning it put it elsewhere as well?

**Comment by devoncarew** [comment]
Just share currently, and don't envision it elsewhere right now.
