### ISSUE TITLE
upgrade to sdk upgrade to 1.11.0

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-services#229]
It'll be released shortly. We'll need to rev. the analyzer, compiler_unsupported, and the analysis server version.

**Comment by devoncarew** [comment]
How's this looking? We're on `Dart SDK 1.10.1` currently, and SDK 1.11.1 is the latest stable sdk release.

**Comment by lukechurch** [comment]
Testing looks good. I'm routing all the traffic to 1.11 now. I shouldn't have close this issue before then.

Have you upgraded the compiler package to 1.11.1, or want to wait to 1.12?

**Comment by lukechurch** [comment]
![image](https://cloud.githubusercontent.com/assets/2978182/8565363/8af9a312-2555-11e5-9448-53f93f9e32e2.png)

**Comment by devoncarew** [comment]
I'll investigate 1.11.1 - the repo change may have made this more difficult.

**Comment by devoncarew** [comment]
1.11.1 of compiler_unsupported is available now

**Comment by lukechurch** [comment]
SG. I'll rev in a few hours, close out this issue for now that we have a tracking issue for migrating to 1.11.1.
