### ISSUE TITLE
Datastore cache rather than memcache compilation results

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-services#234]
Currently we only store compile results in memcache, we should store them in a datastore cache tied to the version of compiler. This would allow considerably improved reliability and performance for less frequent but load-spiking pages - which we can expect a lot more of once DartPad is embedded in other sites.

**Comment by devoncarew** [comment]
Can we just increase the time to live of items in the memcache? And, prefix the key with the compiler version?

It would be great not to have to implement parts of memcache on top of datastore...

**Comment by lukechurch** [comment]
Prefixing the key might work. The way we're using memcache without backing it with a datastore is pretty unusual. It's far more common to follow the pattern suggested above of using datastore and then memcache as an accelerator. There may even be a library that does this for us.

**Comment by devoncarew** [comment]
not currently planned
