### ISSUE TITLE
Tracking issue for compute engine performance

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-services#25]
f1-micro (1 vCPU, 0.6 GB memory) (**OOM**):
```
[analyzer.hello      :    0.754ms]
[analyzer.hellohtml  :    1.800ms]
[analyzer.sunflower  :   12.225ms]
[dart2js.hello       : 2126.199ms]
Segmentation fault
```

**Comment by sgjesse** [comment]
For App Engine Managed VMs you specify the machine you want in the `app.yaml` like this:

```
resources:
  cpu: .5
  memory_gb: 1.3
```

A GCE machine type with at least these resources will then be allocated. See teh section "Resource settings" in https://cloud.google.com/appengine/docs/python/managed-vms/.

**Comment by lukechurch** [comment]
Thanks @sgjesse

**Comment by lukechurch** [comment]
@devoncarew Do you mind if I move this to a wiki so I can use the dart-services Issues as a todo list?

**Comment by devoncarew** [comment]
Sounds good; I would like to have some of this info available somewhere.

**Comment by devoncarew** [comment]
Closing; I'll move the info into a wiki.

**Comment by devoncarew** [comment]
(https://github.com/dart-lang/dart-services/wiki/GCE-Performance)
