### ISSUE TITLE
Version data is being pulled from the wrong place

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-services#288]
We should be pulling version data from the version of Analyzer and the Dart2JS wrapper rather than from the modules or env-vars

**Comment by devoncarew** [comment]
@lukechurch, is this addressed now? We're returning the version info from the sdk we're using (w/ the move away from compiler_unsupported).

**Comment by lukechurch** [comment]
Yeah, this will be fixed on the next push
