### ISSUE TITLE
New function syntax crashes Dartpad

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-services#316]
_From @matanlurey on July 21, 2017 20:21_

DartPad:
https://dartpad.dartlang.org/269de5e20f399ffc9b48c4b3ea3c67a1

```dart
void main() {
  for (int i = 0; i < 5; i++) {
    print('hello ${i + 1}');
  }
}

// Works.
T runLogged1<T>(T Function<T>() run) => run();

// Works.
T runLogged2<T>({T Function<T>() run}) => run();

// Works.
void runLogged3(void Function() run) => run();

// Works.
void runLogged4({void Function() run}) => run();

// Crashes the Dart Analyzer, and I no longer get any analysis completion.
T runLogged<T>(
  T Function<T>() run, {
  String name: 'crosscheck',
  void Function(String message) onLog,
}) => run();
```

_Copied from original issue: dart-lang/sdk#30229_

**Comment by devoncarew** [comment]
_From @bwilkerson on July 21, 2017 22:4_

@lukechurch I think this should be fixed in the latest dev release. Has DartPad been updated? If not, do we have a schedule for updating it?

**Comment by devoncarew** [comment]
_From @bwilkerson on July 25, 2017 18:59_

@devoncarew Do you know whether DartPad has been updated?

**Comment by devoncarew** [comment]
It's on `1.24.0`; @lukechurch  is on vacation but back in a few.

**Comment by devoncarew** [comment]
_From @a-siva on August 1, 2017 20:32_

Under which area does dartpad fall under?

**Comment by lukechurch** [comment]
@bwilkerson We generally don't update DartPad for dev releases, only for fairly unusual issues. I'll begin the process of updating to the latest stable, ETA lunchtime West Coast time

**Comment by lukechurch** [comment]
DartPad is now at ```1.24.2``` and still exhibits this problem. Is there a plan to release a ```1.24.3``` release including the fix?

@devoncarew @bwilkerson

**Comment by lukechurch** [comment]
@mit-mit Any thoughts?

**Comment by bwilkerson** [comment]
I'm not aware of any plans, but we might want to update to the latest dev build. We might want dartpad to start tracking dev builds rather than stable builds in general.

**Comment by devoncarew** [comment]
I think this is a good idea. We'll want it tracking dev builds in order to participate in the new dart 2.0 flag.

**Comment by lukechurch** [comment]
Fixed as part of running edge versions of Analysis Server
