### ISSUE TITLE
Use compiler from SDK not from image

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-services#327]
dart-services is currently using the Analysis server from a specific SDK version but pulling the compiler from the GAE image, due to a problem starting the snapshot from from image.

This results in version skew between analysis and compilation.

**Comment by devoncarew** [comment]
@jcollins-g, is this still currently the case?

**Comment by devoncarew** [comment]
I don't believe the host sdk is used anymore (for either compilation or analysis).

**Comment by devoncarew** [comment]
It looks like we're still doing this: https://github.com/dart-lang/dart-services/blob/5be89c28a28fe026fba0b0973c873f2187a07423/lib/src/compiler.dart#L82

**Comment by jcollins-g** [comment]
Yep.  Removing the workaround leads to deployment errors.  Looking at possible reasons why.
