### ISSUE TITLE
our uptime service should analyze and compile dart:html samples

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-services#58]
The dart code we analyze and compile for the uptime service should reference dart:html.

**Comment by devoncarew** [comment]
@lukechurch

**Comment by lukechurch** [comment]
Yeah, I agree. Let me see whether we get the server messaging fixed up tomorrow. 
If not, I'm probably going to put in a GET end point that we can use to drive this.

Either way, should be easy to adjust

**Comment by lukechurch** [comment]
Tracking update: http://uptime.statuscake.com/?TestID=6FVej0AP1A
