### ISSUE TITLE
uptime service should fuzz the code we compile

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-services#59]
We should either fuzz the code we compile w/ the uptime service (change a comment w/ a timestamp), or pass a no cache variable in the call. This will give us a better sense for how the compilation servers are performing.

**Comment by devoncarew** [comment]
@lukechurch

**Comment by lukechurch** [comment]
Fuzzing the code is really hard with the current infrastructure. We do that on the load testing where we control the driver, but not on StatusCake.

I already have : https://github.com/dart-lang/dart-services/issues/16 open for adding a URL property or HTTP property for turning off the memchache. So closing for now as a duplicate.
