### ISSUE TITLE
How about using the 'shelf_cors' package 

### ISSUE THREAD

**Issue by gmosx** [dart-lang/dart-services#60]
How about using the 'shelf_cors' package instead of a custom version? I am open to any suggestions to make it more suitable for dart-services.

**Comment by devoncarew** [comment]
Looks good; we weren't aware of the package. It looks like `shelf_cors` supports OPTIONS and we can (optionally) use our own custom CORS headers if we want. Adding @lukechurch to see if he has opinions, but generally it looks like it would work just fine. If you want to send a PR, patches welcome :)

**Comment by gmosx** [comment]
OK, I will send you a PR tomorrow.

**Comment by devoncarew** [comment]
Done - https://github.com/dart-lang/dart-services/pull/61.
