### ISSUE TITLE
Executing JS returned by /compile

### ISSUE THREAD

**Issue by danschultz** [dart-lang/dart-services#78]
How does one execute the JS returned by `/compile`?

**Comment by lukechurch** [comment]
Usually what you want to do is to inject it into an IFrame.

Sorry to bounce you around - this code is actually done in the dart-pad client here: https://github.com/dart-lang/dart-pad/blob/138eef184f0971e1c3dc433b4cd6eba053410dbd/lib/services/execution_iframe.dart

The decoration methods are for routing the print and errors back into the parent frame, you could ignore them to get started with.

You'll then see that the messages get sent with:  frame.contentWindow.postMessage where m is the command object being sent.

This is then interpreted by the message handling code inside the frame here: https://github.com/dart-lang/dart-pad/blob/master/web/frame.html

Which actually installs the JS.

Does this help? If you get stuck, please let me know and we can try and put together a stripped down sample.

**Comment by devoncarew** [comment]
Yup, and to add, some playgrounds provide a small bit of html that you can embed on a page (in an iframe), which itself will take care of the details of embedding the execution iframe. We don't have one of those yet, but will create one for use in dartdoc documentation.

**Comment by devoncarew** [comment]
Also adding an example from dartlab: https://github.com/dartlab/dartlab/blob/master/lib/dart_preview.html.

**Comment by danschultz** [comment]
Awesome, thanks guys. This is super helpful.
