### ISSUE TITLE
push to restore hosted dependencies

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-services#80]
We're now using forked git deps for some core libraries (https://github.com/dart-lang/dart-services/blob/master/pubspec.yaml#L15). We'll want to go back to non-forked hosted deps for the analyzer, and possibly git deps for the other packages.

**Comment by devoncarew** [comment]
It looks like we're forking three packages:
```
analysis_server: git://github.com/lukechurch/dart-analysis-server-temp-working.git
analyzer: git://github.com/lukechurch/dart-analyzer-temp-working.git
dart_style: git://github.com/lukechurch/dart_style.git
```
I'd like to unfork the `analyzer` package, remove our dep on `dart_style`, and look at either using a hosted version of `analysis_server` or invoking the snapshot of it in the sdk.

@lukechurch

**Comment by lukechurch** [comment]
@devoncarew See internal thread.

**Comment by lukechurch** [comment]
Also see #223

**Comment by lukechurch** [comment]
@bwilkerson @stereotype441 @devoncarew @clayberg @danrubel 

This is now deforked. Thank you for your help!
