### ISSUE TITLE
completions for a `DivElement` are duplicated

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-services#90]
![screen shot 2015-03-24 at 11 01 13 pm](https://cloud.githubusercontent.com/assets/1269969/6819155/c13d97aa-d279-11e4-9d3e-159dbf96245c.png)

(will follow up with a code example)

**Comment by devoncarew** [comment]
dartpad.dartlang.org/d593ff0011c8a24bb8b1

**Comment by kasperpeulen** [comment]
Seems to be that one is a getter and the other is a setter:

![image](https://cloud.githubusercontent.com/assets/1035299/6907582/c666e70a-d737-11e4-8550-36162ee5c347.png)

**Comment by devoncarew** [comment]
Good find; looks like the issue is more about differentiating them in the UI.
